
package com.mycompany.sistema_ventas2;


import java.util.ArrayList;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {
    public static ArrayList <Cliente> listaClientes = new ArrayList <Cliente>();
    public static ArrayList <Producto> listaProductos = new ArrayList <Producto>();
    public static ArrayList <Pedido> listaPedidos = new ArrayList <Pedido>();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        button1 = new java.awt.Button();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnuCerrar = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        MnuVentas = new javax.swing.JMenu();
        MnuNuevaVenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MnuProductos = new javax.swing.JMenuItem();
        MnuClientes = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MnuReporte = new javax.swing.JMenuItem();
        jmenupago = new javax.swing.JMenu();
        MnuPago = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        button1.setLabel("button1");

        jMenuItem4.setText("jMenuItem4");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(715, 512));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel4.setText("Importaciones PEJAF I.R.L");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 460, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 270));

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        MnuCerrar.setText("Cerrar el programa");
        MnuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(MnuCerrar);

        jMenuItem6.setText("Ayuda");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        MnuVentas.setText("Ventas");
        MnuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuVentasActionPerformed(evt);
            }
        });

        MnuNuevaVenta.setText("Generar Venta");
        MnuNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuNuevaVentaActionPerformed(evt);
            }
        });
        MnuVentas.add(MnuNuevaVenta);

        jMenuBar1.add(MnuVentas);

        jMenu3.setText("Mantenimiento");

        MnuProductos.setText("Productos");
        MnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuProductosActionPerformed(evt);
            }
        });
        jMenu3.add(MnuProductos);

        MnuClientes.setText("Clientes");
        jMenu3.add(MnuClientes);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Reportes");

        MnuReporte.setText("Reporte venta");
        MnuReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuReporteActionPerformed(evt);
            }
        });
        jMenu5.add(MnuReporte);

        jMenuBar1.add(jMenu5);

        jmenupago.setText("Pago");

        MnuPago.setText("Pagar compra");
        jmenupago.add(MnuPago);

        jMenuBar1.add(jmenupago);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void MnuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuVentasActionPerformed
    
    }//GEN-LAST:event_MnuVentasActionPerformed

    private void MnuNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuNuevaVentaActionPerformed
        Venta v = new Venta(this,true);
        v.setVisible(true);
        
        if (v.getC() != null){
            listaClientes.add(v.getC());
        }else {
            JOptionPane.showMessageDialog(null, "Ingrese datos","Accion errada", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(v.getP() != null){
            listaPedidos.add(v.getP());
    }else {
            JOptionPane.showMessageDialog(null, "Ingrese datos","Accion errada", JOptionPane.INFORMATION_MESSAGE);
        }
        if(v.getPro() !=null){
            listaProductos.add(v.getPro());
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese datos","Accion errada", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_MnuNuevaVentaActionPerformed

    private void MnuReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuReporteActionPerformed
          ReporteVenta r = new ReporteVenta(this,true);
          r.setVisible(true);
          
    }//GEN-LAST:event_MnuReporteActionPerformed

    private void MnuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuCerrarActionPerformed
        
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de cerrar el programa?","Confirmacion",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(respuesta == JOptionPane.YES_OPTION){
            dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_MnuCerrarActionPerformed

    private void MnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuProductosActionPerformed
        Productos p = new Productos(this,true);
        p.setVisible(true);
    }//GEN-LAST:event_MnuProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnuCerrar;
    private javax.swing.JMenuItem MnuClientes;
    private javax.swing.JMenuItem MnuNuevaVenta;
    private javax.swing.JMenuItem MnuPago;
    private javax.swing.JMenuItem MnuProductos;
    private javax.swing.JMenuItem MnuReporte;
    private javax.swing.JMenu MnuVentas;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenu jmenupago;
    // End of variables declaration//GEN-END:variables
}
