/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.sistema_ventas2;

/**
 *
 * @author xergg
 */
public class ReporteVenta extends javax.swing.JDialog {

    /**
     * Creates new form ReporteVenta
     */
    public ReporteVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        listarClientes();
    }
    
    
    public void listarClientes(){
         txaReporte.setText("");
    
        for (Cliente c : Principal.listaClientes) {
            txaReporte.append("Nombre: " + c.getNombre());
            txaReporte.append("\nDNI: " + c.getDni());
            txaReporte.append("\nTelefono: " + c.getTelefono());
            txaReporte.append("\nDireccion: " + c.getDireccion() + "\n");
        }

        for (Pedido p : Principal.listaPedidos) {
            txaReporte.append("\nPedido: " + p.getCodigo());
            for (Producto pro : p.getListaProductos()) {
                txaReporte.append("\n  Producto: " + pro.getNombre());
                txaReporte.append("\n  Cantidad: " + pro.getCantidad());
                txaReporte.append("\n  Precio: " + pro.getPrecio());
                txaReporte.append("\n  Stock: " + pro.getStock());
            }
        }

        for (Producto pro : Principal.listaProductos) {
            txaReporte.append("\nProducto: " + pro.getNombre());
            txaReporte.append("\nCantidad: " + pro.getCantidad());
        }
                
        
}
    /**{
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaReporte = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Ventas");
        setMinimumSize(new java.awt.Dimension(370, 365));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaReporte.setColumns(20);
        txaReporte.setRows(5);
        txaReporte.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista"));
        jScrollPane1.setViewportView(txaReporte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 28, 430, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReporteVenta dialog = new ReporteVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaReporte;
    // End of variables declaration//GEN-END:variables
}
